packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    '@antfu/utils': ^9.3.0
    '@iconify/json': ^2.2.408
    '@types/codemirror': ^5.60.17
    '@types/node': ^24.10.1
    '@unocss/eslint-config': ^66.5.7
    '@unocss/eslint-plugin': ^66.5.7
    '@vitejs/plugin-vue': ^6.0.2
    '@vue/compiler-sfc': ^3.5.24
    bumpp: ^10.3.1
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    rimraf: ^6.1.0
    serve: ^14.2.5
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.3
    unbuild: ^3.6.1
    unocss: ^66.5.7
    unplugin-auto-import: ^20.2.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-router: ^0.17.0
    vite: ^7.2.2
    vue-tsc: ^3.1.4
  frontend:
    '@vueuse/core': ^14.0.0
    '@vueuse/router': ^14.0.0
    codemirror: ^5.65.16
    codemirror-theme-vars: ^0.1.2
    comlink: ^4.4.2
    diff-match-patch-es: ^1.0.1
    echarts: ^6.0.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^2.0.0
    pinia: ^3.0.4
    splitpanes: ^4.0.4
    vis-data: ^8.0.3
    vis-network: ^10.0.2
    vite-dev-rpc: ^1.1.0
    vite-hot-client: ^2.1.0
    vue: ^3.5.24
    vue-echarts: ^8.0.1
    vue-router: ^4.6.3
  prod:
    '@nuxt/kit': ^4.2.1
    ansis: ^4.2.0
    error-stack-parser-es: ^1.0.5
    obug: ^2.0.0
    open: ^11.0.0
    sirv: ^3.0.2
    unplugin-utils: ^0.3.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
